"""Golden fixtures must satisfy the same invariants as producer output.

WHY THIS EXISTS.

A committed fixture is an UNVALIDATED INPUT that every downstream test trusts. When
`fixtures/cap-table/scenarios.json` encoded a SAFE as "5% ownership, 550,000 shares" against an
11,000,000-share base -- 550,000 shares is 4.76%, not 5% -- that inconsistency was staged into every
cap-table compose, visualize and invariant test by `compose_invocations.py`. All of them passed. The
fixture laundered a producer defect through ten files' worth of green tests, and it had to be
regenerated by hand as part of the fix (`d4fdb05`).

This is a distinct failure mode from the four in the post-mortem, and none of their counter-measures
touch it: the producer tests asserted against the producer, the renderer tests asserted against the
fixture, and nobody asserted the fixture was internally coherent.

SCOPE, deliberately narrow. This checks arithmetic relationships that must hold for ANY correct
fixture -- percentages against the counts that produce them -- not the specific values, which are
free to change. A fixture is allowed to be unrealistic; it is not allowed to be self-contradictory.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

FIXTURES = Path(__file__).resolve().parent / "fixtures"

# Fixtures carrying computed cap-table scenarios. Listed explicitly rather than globbed: a new
# fixture should be a deliberate addition here, so "no fixture was checked" cannot look like "every
# fixture passed" -- the same registry discipline the paid-lane and producer-rejection checks use.
CAP_TABLE_SCENARIO_FIXTURES = [
    FIXTURES / "cap-table" / "scenarios.json",
]


def _cap_implied_entries(scenarios: dict) -> list[tuple[str, dict, float | None]]:
    """(safe_id, per_safe_entry, company_capitalization) for every cap-implied SAFE."""
    out = []
    for scenario in scenarios.get("scenarios") or []:
        computed = scenario.get("computed_outputs") or {}
        total = computed.get("company_capitalization")
        for entry in computed.get("per_safe") or []:
            if entry.get("branch") == "cap_implied":
                out.append((entry["id"], entry, total))
    return out


@pytest.mark.parametrize("path", CAP_TABLE_SCENARIO_FIXTURES, ids=lambda p: p.parent.name)
def test_fixture_cap_implied_is_self_consistent(path: Path) -> None:
    """A fixture's stated ownership must equal the ownership its stated share count delivers.

    This is the same relationship the producer now enforces on itself. Asserting it on the fixture
    too is the point: a fixture is the one input to the test suite that the test suite does not
    otherwise check.
    """
    assert path.is_file(), f"registered fixture is missing: {path}"
    scenarios = json.loads(path.read_text(encoding="utf-8"))

    entries = _cap_implied_entries(scenarios)
    assert entries, (
        f"{path.name} has no cap-implied SAFE entries — either the fixture changed shape or this "
        "check is now testing nothing. A registry entry that matches zero cases is worse than no "
        "entry, because it reports as a pass."
    )

    for safe_id, entry, total in entries:
        stated = entry.get("cap_implied_ownership")
        shares = entry.get("cap_implied_shares")
        assert stated is not None and shares, f"{safe_id}: incomplete cap-implied entry {entry!r}"
        assert total, (
            f"{safe_id}: the fixture records no company_capitalization, so its percentages cannot be "
            "checked against its share counts. Regenerate it from the producer."
        )
        realised = shares / total
        assert abs(realised - stated) < 1e-6, (
            f"{path.name} / {safe_id}: fixture states {stated:.2%} ownership but its {shares:,.0f} "
            f"shares deliver {realised:.2%} of the {total:,.0f}-share base. Every test that stages "
            "this fixture inherits the contradiction and still passes."
        )


@pytest.mark.parametrize("path", CAP_TABLE_SCENARIO_FIXTURES, ids=lambda p: p.parent.name)
def test_fixture_cap_implied_denominator_closes(path: Path) -> None:
    """The recorded denominator must equal the base plus the shares it produced.

    The check with content. `shares / total == ownership` can be satisfied by construction if all
    three are derived from one another; this one says the fixed point actually closed, which is a
    fact about the solve rather than a restatement of a definition.
    """
    scenarios = json.loads(path.read_text(encoding="utf-8"))
    cap_state_path = path.parent / "cap_state.json"
    if not cap_state_path.is_file():
        pytest.skip(f"no cap_state.json beside {path.name} to supply the pre-financing base")

    pre_fd = (json.loads(cap_state_path.read_text(encoding="utf-8")).get("as_converted_totals") or {}).get(
        "fully_diluted_shares"
    )
    if not pre_fd:
        pytest.skip("cap_state fixture records no fully_diluted_shares")

    for scenario in scenarios.get("scenarios") or []:
        computed = scenario.get("computed_outputs") or {}
        total = computed.get("company_capitalization")
        cap_implied = [e for e in computed.get("per_safe") or [] if e.get("branch") == "cap_implied"]
        if not (total and cap_implied):
            continue
        closed = pre_fd + sum(e["cap_implied_shares"] for e in cap_implied)
        assert abs(closed - total) < 1e-6 * max(1.0, total), (
            f"{path.name}: company_capitalization is {total:,.0f} but the pre-financing base "
            f"({pre_fd:,.0f}) plus its converting shares is {closed:,.0f}"
        )
