#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Insert coaching commentary into report.md at the compose-emitted marker.

Deterministic replacement for the Context B agent-side insertion protocol:
the 6-state Grep idempotency matrix, the Edit-via-uuid-marker choreography,
and the run_id-parity verification previously expressed as natural-language
agent-body instructions. The agent now only composes the commentary text;
this script does everything mechanical.

Usage:
    echo '{"commentary_markdown": "..."}' | \
        python insert_coaching.py --report <report.md> \
            --marker '<!-- COACHING_INSERTION_POINT_a1b2c3d4 -->' \
            --verify-artifact <inputs.json> --verify-artifact <sizing.json>

    python insert_coaching.py --commentary-file <staged.json> \
        --report <report.md> --marker '<exact marker>'

Input JSON (stdin or --commentary-file): {"commentary_markdown": "<text>"}.
The commentary text is inserted verbatim as "## Coaching Commentary\\n\\n"
+ text, replacing the exact marker string (never the marker prefix).

Idempotency matrix on (commentary_count, marker_count) in report.md:
    (0, 1)  -> insert (the normal path)
    (1, 0)  -> already inserted; no-op success (resume-safe)
    all other states -> exit 1 with the same diagnostic strings the agent
    bodies used, so existing triage docs stay valid.

run_id parity: each --verify-artifact JSON must carry metadata.run_id and
all values must be equal. Parity runs BEFORE the write so a parity failure
leaves report.md untouched.

Write strategy: the new content is built fully in memory, then written in
a single in-place pass (open "w" on the same path). Never delete/recreate
and never os.replace: we write report.md in place by rule. (Older Cowork
hosts refused a delete or a rename over a file under outputs/; newer ones
allow it, and other scripts do rename there, so this is a choice, not a
platform limit.)

Output: JSON receipt to stdout (--pretty for indented output; -o writes
the receipt to a file and emits a confirmation receipt to stdout).

Check-record declaration: a report whose compose wrote
    <!-- COACHING_REQUIRES_CHECK_RECORD run_id=<run> -->
beside the marker takes commentary only with `check_record` in the envelope: the path of a JSON record whose
`action` is present and not "findings", whose `run_id` is <run> (always: the check reads the run before it can fail
open, and refuses without one), and whose `checked_commentary_sha256` is the sha256 of this commentary. Otherwise it
is blocked and report.md is untouched. The declaration is removed on insert. A report with no declaration is handled
exactly as before, whatever the envelope carries.

Exit codes:
    0 = inserted or already inserted (receipt on stdout)
    1 = blocked (diagnostic JSON on stdout, human-readable line on stderr)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

COMMENTARY_HEADING = "## Coaching Commentary"
# A report that declares its commentary needs a passing check record. Written by a skill's compose beside the
# marker, so the requirement travels with the report rather than depending on a flag someone must remember.
_DECLARATION_RE = re.compile(r"<!-- COACHING_REQUIRES_CHECK_RECORD run_id=(\S+) -->\n?")
# The attribution line every compose script writes after the insertion marker. A coach told that every
# report it presents ends with it treated its commentary as one and wrote it too, so the founder read it
# twice. A trailing copy in the commentary is dropped when the report already carries one after the
# marker -- and only then, and only at the end: the coach quoting the line elsewhere is its own text.
FOOTER_PREFIX = "*Generated by [founder skills]"
_TRAILING_FOOTER_RE = re.compile(
    r"(?:\n[ \t]*-{3,}[ \t]*)?\n?[ \t]*" + re.escape(FOOTER_PREFIX) + r"[^\n]*\*[ \t]*\s*\Z"
)


def _drop_duplicate_footer(commentary: str, report_after_marker: str) -> tuple[str, bool]:
    """(commentary without a trailing footer, whether one was dropped). A no-op unless the report's text
    after the marker already carries the footer."""
    if FOOTER_PREFIX not in report_after_marker:
        return commentary, False
    trimmed = _TRAILING_FOOTER_RE.sub("", "\n" + commentary.rstrip())
    if trimmed == "\n" + commentary.rstrip():
        return commentary, False
    return trimmed.lstrip("\n"), True


# This run's id once run_id parity has passed, and the report it is about. Only then does the run's
# status file hear about the outcome: a block before parity is not known to be this run's.
_STATUS_RUN: dict[str, str] = {}


def _status_write(outcome: str) -> None:
    """Tell the run's status file what happened, when the run has a gate ledger. Never changes stdout or
    the exit code: a failure is one stderr line. With no `run_ref.json` beside the report, nothing runs.
    """
    run_id = _STATUS_RUN.get("run_id")
    report = _STATUS_RUN.get("report")
    if not run_id or not report:
        return
    run_dir = os.path.dirname(report)
    if not os.path.isfile(os.path.join(run_dir, "handoff", run_id, "run_ref.json")):
        return
    try:
        here = os.path.dirname(os.path.abspath(__file__))
        if here not in sys.path:
            sys.path.append(here)
        import _run_status

        paths = _run_status.locate_from_run_dir(run_dir, run_id)
        if paths is None:
            return
        if outcome == "blocked":
            _run_status.coaching_blocked(paths)
            return
        status = _run_status.complete_after_coaching(paths, report, _STATUS_RUN.get("report_json") or None)
        if status.get("status") != "complete" and status.get("status") not in _run_status.FINAL_STATUSES:
            print(
                f"note: the coaching is in, but the run is {status.get('status')} on {status.get('waiting_on')}; "
                "it completes once that gate is answered",
                file=sys.stderr,
            )
    except Exception as e:
        print(f"warning: the run status was not updated: {e}", file=sys.stderr)


def _blocked(reason: str, pretty: bool, output: str | None) -> int:
    payload: dict[str, object] = {"status": "blocked", "reason": reason}
    _emit(payload, pretty, output)
    print(f"BLOCKED: {reason}", file=sys.stderr)
    _status_write("blocked")
    return 1


def _emit(payload: dict[str, object], pretty: bool, output: str | None) -> None:
    indent = 2 if pretty else None
    out = json.dumps(payload, indent=indent) + "\n"
    if output:
        abs_path = os.path.abspath(output)
        parent = os.path.dirname(abs_path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as f:
            f.write(out)
        receipt = {"written": abs_path, "bytes": len(out.encode("utf-8"))}
        sys.stdout.write(json.dumps(receipt) + "\n")
    else:
        sys.stdout.write(out)


def _load_commentary(commentary_file: str | None) -> tuple[str | None, str | None, object]:
    """Return (commentary_markdown, error_reason, the envelope's `check_record`)."""
    try:
        if commentary_file:
            with open(commentary_file, encoding="utf-8") as f:
                raw = f.read()
        else:
            raw = sys.stdin.read()
    except OSError as exc:
        return None, f"cannot read commentary input: {exc}", None
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        return None, f"commentary input is not valid JSON: {exc}", None
    if not isinstance(parsed, dict):
        return None, "commentary input must be a JSON object", None
    commentary = parsed.get("commentary_markdown")
    if not isinstance(commentary, str) or not commentary.strip():
        return None, "commentary_markdown missing or empty", None
    return commentary, None, parsed.get("check_record")


def _check_record_reason(declared_run: str, record_path: object, commentary: str) -> str | None:
    """Why a declared report refuses this commentary, or None when its check record passes it."""
    import hashlib

    lead = "this report takes commentary only with a passing check record"
    if not isinstance(record_path, str) or not record_path:
        return f"{lead}; the commentary came with none -- run the report's check step and insert what it releases"
    try:
        with open(record_path, encoding="utf-8") as f:
            record = json.load(f)
    except (OSError, json.JSONDecodeError):
        return f"{lead}; no readable check record at {record_path}"
    if not isinstance(record, dict):
        return f"{lead}; the check record at {record_path} is not a JSON object"
    action = record.get("action")
    if not isinstance(action, str) or action == "findings":
        return f"{lead}; the check did not pass this commentary (action: {action})"
    if record.get("run_id") != declared_run:
        return f"{lead}; the check record is from run {record.get('run_id')}, not {declared_run}"
    if record.get("checked_commentary_sha256") != hashlib.sha256(commentary.encode("utf-8")).hexdigest():
        return f"{lead}; the commentary is not the text the check passed"
    return None


def _matrix_reason(commentary_count: int, marker_count: int) -> str | None:
    """The 6-state idempotency matrix. None means 'proceed' or 'already
    inserted' (the two success states, distinguished by the caller)."""
    if commentary_count >= 2:
        return f"duplicate commentary detected (count={commentary_count})"
    if marker_count >= 2:
        return f"compose emitted multiple markers (count={marker_count}); compose bug"
    if commentary_count == 1 and marker_count == 1:
        return "partial-state corruption: commentary present but marker not consumed"
    if commentary_count == 0 and marker_count == 0:
        return (
            "compose did not emit insertion marker — or report.md may be "
            "truncated by an interrupted insert; re-run "
            "`compose_report.py --write-md` and retry"
        )
    return None


def _verify_run_id_parity(artifact_paths: list[str]) -> tuple[str | None, str | None]:
    """Return (run_id, error_reason). All artifacts must carry an equal
    metadata.run_id."""
    run_ids: dict[str, str] = {}
    for path in artifact_paths:
        name = os.path.basename(path)
        if not os.path.isfile(path):
            return None, f"{name} not found at {path}"
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as exc:
            return None, f"run_id mismatch: {name} unreadable as JSON ({exc})"
        run_id = None
        if isinstance(data, dict):
            metadata = data.get("metadata")
            if isinstance(metadata, dict):
                run_id = metadata.get("run_id")
        if not isinstance(run_id, str) or not run_id:
            return None, f"run_id mismatch: {name} has no metadata.run_id"
        run_ids[name] = run_id
    distinct = sorted(set(run_ids.values()))
    if len(distinct) > 1:
        detail = ", ".join(f"{k}={v}" for k, v in sorted(run_ids.items()))
        return None, f"run_id mismatch: {detail}"
    return (distinct[0] if distinct else None), None


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Insert coaching commentary into report.md")
    p.add_argument("--report", required=True, help="Path to report.md")
    p.add_argument(
        "--marker",
        required=True,
        help="EXACT insertion marker string emitted by compose (never the prefix)",
    )
    p.add_argument(
        "--commentary-file",
        help="Read commentary JSON from this file instead of stdin",
    )
    p.add_argument(
        "--verify-artifact",
        action="append",
        default=[],
        metavar="PATH",
        help="JSON artifact whose metadata.run_id must match all others (repeatable)",
    )
    p.add_argument(
        "--report-json",
        help="Path to report.json. Its `report_markdown` is a SECOND COPY of report.md, and "
        "writing back to the markdown alone left it holding the pre-insertion text plus a raw "
        "uuid insertion marker — measured 5,592 characters adrift on a live run. Named-but-absent "
        "is fatal; omitted is fine (not every caller composes a report.json).",
    )
    p.add_argument("--pretty", action="store_true", help="Pretty-print JSON output")
    p.add_argument("-o", "--output", help="Write receipt to file instead of stdout")
    return p.parse_args()


def _scan_commentary(commentary: str) -> dict[str, list[str]]:
    """Report internal tokens in the coaching commentary. Never rewrites it.

    WHY THIS LIVES HERE. Each skill's `compose_report.py` scans the report it assembles, but the
    Coaching Commentary is not in that string — compose emits a marker, and this script replaces the
    marker afterwards. So the compose-time scan structurally CANNOT see the commentary, which is
    model-authored prose and therefore the likeliest place for an internal token to appear. This is the
    one shared place every skill's commentary passes through.

    REPORTS, does not substitute. Two reasons: this script's contract is verbatim insertion (its test
    suite pins that, and transport fidelity for quotes/newlines is the reason the envelope exists), and
    commentary may legitimately quote the founder's OWN field or column names, which we must not
    silently reword. The actionable fix is upstream in the coaching dispatch template.

    Non-blocking by design — a token in coaching text must never cost a founder their report. Delivery
    enforcement, where a skill has it, belongs in that skill's verify gate.
    """
    try:
        shared = os.path.dirname(os.path.abspath(__file__))
        if shared not in sys.path:
            sys.path.insert(0, shared)
        import _founder_text  # type: ignore[import-not-found]
    except ImportError:
        return {"enums": [], "filenames": []}
    found: dict[str, list[str]] = _founder_text.scan(commentary)
    for token in found["enums"]:
        print(
            f"note: coaching commentary contains the internal token '{token}' — a founder cannot act on it",
            file=sys.stderr,
        )
    for name in found["filenames"]:
        print(
            f"note: coaching commentary names the internal file '{name}' — drop the reference",
            file=sys.stderr,
        )
    return found


def _sync_report_json(path: str, markdown: str) -> str | None:
    """Rewrite report.json's `report_markdown` to match report.md. Error string, or None.

    `report_markdown` is not a derived view — it is the SOURCE `compose_report.py` writes
    report.md from, and it is also what ~200 test sites across six skills read to inspect
    report content. So it cannot simply be dropped from the serialized artifact; it has to be
    kept true. Everything else in the file is preserved byte-for-byte except this one key.

    Rewritten in place with no delete/rename, by rule, the same way the markdown write is (see the
    module docstring).
    """
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except OSError as exc:
        return f"--report-json named {path} but it is not readable: {exc}"
    except json.JSONDecodeError as exc:
        return f"--report-json at {path} is not valid JSON: {exc}"
    if not isinstance(data, dict):
        return f"--report-json at {path} is not a JSON object"
    if "report_markdown" not in data:
        return f"--report-json at {path} has no `report_markdown` key — is it a composed report.json?"
    data["report_markdown"] = markdown
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(json.dumps(data, indent=2) + "\n")
    except OSError as exc:
        return f"write-back to {path} failed: {exc}"
    return None


def main() -> None:
    args = parse_args()
    pretty: bool = args.pretty
    output: str | None = args.output

    try:
        with open(args.report, encoding="utf-8") as f:
            report_text = f.read()
    except OSError as exc:
        sys.exit(_blocked(f"report.md not readable at {args.report}: {exc}", pretty, output))

    # CHECKED BEFORE ANY WRITE. A named-but-unreadable report.json discovered afterwards would
    # leave report.md inserted and the JSON stale — the exact divergence this flag exists to
    # close, reintroduced by the fix's own error path.
    if args.report_json and not os.path.isfile(args.report_json):
        sys.exit(_blocked(f"--report-json named {args.report_json} but no file is there", pretty, output))

    commentary_count = report_text.count(COMMENTARY_HEADING)
    marker_count = report_text.count(args.marker)

    reason = _matrix_reason(commentary_count, marker_count)
    if reason is not None:
        sys.exit(_blocked(reason, pretty, output))

    run_id, parity_error = _verify_run_id_parity(args.verify_artifact)
    if parity_error is not None:
        sys.exit(_blocked(parity_error, pretty, output))
    if run_id:
        _STATUS_RUN.update(
            run_id=run_id,
            report=os.path.abspath(args.report),
            report_json=os.path.abspath(args.report_json) if args.report_json else "",
        )

    already_inserted = commentary_count == 1 and marker_count == 0
    if already_inserted:
        # The resume path rewrites nothing, so without this the JSON keeps the marker
        # permanently on exactly the run most likely to follow an interruption.
        if args.report_json:
            err = _sync_report_json(args.report_json, report_text)
            if err is not None:
                sys.exit(_blocked(err, pretty, output))
        _emit(
            {
                "status": "already_inserted",
                "report_path": os.path.abspath(args.report),
                "run_id": run_id,
                "verified_artifacts": len(args.verify_artifact),
            },
            pretty,
            output,
        )
        _status_write("inserted")
        sys.exit(0)

    # State (0, 1): insert.
    commentary, load_error, check_record = _load_commentary(args.commentary_file)
    if load_error is not None or commentary is None:
        sys.exit(_blocked(load_error or "commentary_markdown missing or empty", pretty, output))
    declared = _DECLARATION_RE.search(report_text)
    if declared is not None:
        record_error = _check_record_reason(declared.group(1), check_record, commentary)
        if record_error is not None:
            sys.exit(_blocked(record_error, pretty, output))
        # The declaration has done its job; it never reaches the delivered report.
        report_text = _DECLARATION_RE.sub("", report_text)

    commentary, footer_dropped = _drop_duplicate_footer(commentary, report_text.split(args.marker, 1)[1])
    replacement = f"{COMMENTARY_HEADING}\n\n{commentary.strip()}"
    new_text = report_text.replace(args.marker, replacement, 1)

    # Post-insert self-check on the in-memory content BEFORE touching disk.
    new_commentary_count = new_text.count(COMMENTARY_HEADING)
    new_marker_count = new_text.count(args.marker)
    if new_commentary_count != 1 or new_marker_count != 0:
        sys.exit(
            _blocked(
                f"post-insert self-check failed: commentary count="
                f"{new_commentary_count} (expected 1), marker count="
                f"{new_marker_count} (expected 0) — commentary text may "
                f"contain the heading or the marker string; report.md was "
                f"NOT modified",
                pretty,
                output,
            )
        )

    # Single in-place write pass (no delete/recreate, no os.replace —
    # we write in place by rule; see the module docstring).
    try:
        with open(args.report, "w", encoding="utf-8") as f:
            f.write(new_text)
    except OSError as exc:
        sys.exit(_blocked(f"write-back to {args.report} failed: {exc}", pretty, output))

    if args.report_json:
        err = _sync_report_json(args.report_json, new_text)
        if err is not None:
            sys.exit(_blocked(err, pretty, output))

    _emit(
        {
            "status": "inserted",
            "footer_dropped": footer_dropped,
            "report_path": os.path.abspath(args.report),
            "run_id": run_id,
            "verified_artifacts": len(args.verify_artifact),
            "commentary_bytes": len(commentary.encode("utf-8")),
            "founder_text_findings": _scan_commentary(commentary),
        },
        pretty,
        output,
    )
    _status_write("inserted")
    sys.exit(0)


if __name__ == "__main__":
    main()
