#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["openpyxl", "xlrd", "pdfplumber"]
# ///
"""Corpus test: cap-table extraction against a real-world spreadsheet/PDF corpus.

Designed to run against any folder of cap-table files (a real-world sample
of lawyer-produced cap tables). For each file:
  * Loadability (can openpyxl / xlrd / pdfplumber open it without crashing?)
  * Format detection (Carta / Pulley / OCX fingerprint check via
    extract_cap_table.py mode-detection logic)
  * Sheet + column header inventory (xlsx/xls only)
  * Anonymized aggregate findings (corpus statistics)

Anonymization: filenames are replaced with file_NNN; raw document text is
never stored; per-file sheet/header inventories are reduced to counts; and
sheet/header name aggregates only include names recurring in >= 3 files
(company-specific names — e.g. Carta's "{Company} Cap Table" banner — do
not recur across companies and are excluded).

Usage:
    python3 scripts/corpus_test_captables.py <CORPUS_DIR> [-o report.json]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import warnings
from collections import Counter
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
CAPTABLE_SCRIPTS = REPO / "founder-skills" / "skills" / "cap-table" / "scripts"

# Carta/Pulley sheet-name fingerprints — VERIFIED against real exports
# (corpus 2 contained 13 real Carta exports of varying detail levels).
#
# Carta exports use {Summary, Intermediate, Detailed} Cap Table as their
# top-level sheets. Larger exports add per-share-class ledgers:
# `CS Ledger`, `PS1 Ledger`, `PA1 Ledger`, ..., `Convertible Ledger`,
# `{Plan Name}` for the equity-incentive plan, `Data Warnings`,
# `Summary by Cost Center`, `{Class Prefix} Warrant Ledger`.
#
# Carta puts a banner in rows 2-3 ("{Company} {Sheet Type}" +
# "As of {date} • Generated by") and real headers in **row 5**.
# (This is deterministic for Carta; the freeform fallback's
# header-row heuristic also finds row 5.)
#
# The OCX standard (Carta's optional standardized export format) has
# different sheet names: "Capitalization by Stakeholder", "Voting
# Details", "Context". OCX is rarely used in practice (0/258 in corpus 1,
# 0/14 in corpus 2); the {Summary, Intermediate, Detailed} export is
# Carta's default.
CARTA_PRIMARY_FINGERPRINT = {"Summary Cap Table"}  # minimal Carta export
CARTA_FULL_FINGERPRINT = {"Summary Cap Table", "Intermediate Cap Table", "Detailed Cap Table"}
CARTA_OCX_FINGERPRINT = {"Capitalization by Stakeholder", "Voting Details", "Context"}
PULLEY_FINGERPRINT = {"Ownership"}  # plus contract-specific tabs (SAFEs, Shares, ...)
PULLEY_CONTRACT_TABS = {"Shares", "SAFEs", "Convertible Notes", "Stock Options", "RSAs", "RSUs", "Warrants"}


def detect_format(sheet_names: list[str]) -> str:
    """Classify XLSX as one of: carta | carta_ocx | pulley | freeform.

    Returns `carta` for the default Carta export format (the one all 13
    real-world Carta exports in corpus 2 use). Returns `carta_ocx` for
    the rarely-used OCX standard. Returns `pulley` for Pulley's
    per-contract-type tab layout. Returns `freeform` otherwise.

    Whitespace is stripped from sheet names before comparison (corpus 1
    surfaced trailing-whitespace sheet names like `"Cap Table "`).
    """
    sheets = {s.strip() for s in sheet_names}
    if CARTA_OCX_FINGERPRINT.issubset(sheets):
        return "carta_ocx"
    # Detect Carta by primary fingerprint OR full fingerprint (smaller
    # Carta exports have only Summary Cap Table)
    if CARTA_FULL_FINGERPRINT.issubset(sheets) or CARTA_PRIMARY_FINGERPRINT.issubset(sheets):
        return "carta"
    if PULLEY_FINGERPRINT.issubset(sheets) and PULLEY_CONTRACT_TABS & sheets:
        return "pulley"
    return "freeform"


def load_xlsx(path: Path) -> tuple[bool, dict[str, Any]]:
    """Try to load an XLSX. Returns (ok, info_or_error_dict).

    Handles macOS-dupe `.xlsx(N)` extensions by reading file bytes
    and passing them to openpyxl via BytesIO (openpyxl rejects the path-based
    extension check).
    """
    try:
        import io

        import openpyxl

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            # Use file-bytes path to bypass openpyxl's extension check
            with open(path, "rb") as fp:
                wb = openpyxl.load_workbook(io.BytesIO(fp.read()), read_only=True, data_only=True)
        sheet_names = list(wb.sheetnames)
        sheet_info = {}
        for sn in sheet_names:
            ws = wb[sn]
            # read_only mode doesn't expose .dimensions / .max_row / .max_column
            # for many files; use safe attribute access with defaults.
            sheet_info[sn] = {
                "max_row": getattr(ws, "max_row", None),
                "max_col": getattr(ws, "max_column", None),
            }
        # Row 1 of cap tables is typically a banner/title (e.g. "Acme Cap
        # Table"). Real column headers are usually in rows 2-5. Scan the
        # first 8 rows and pick the row with the most short-ish string
        # cells — that's the column-header row in practice.
        headers_per_sheet = {}
        likely_header_row_per_sheet = {}
        for sn in sheet_names:
            ws = wb[sn]
            try:
                rows_to_scan = list(ws.iter_rows(min_row=1, max_row=8, values_only=True))
            except Exception:
                rows_to_scan = []
            best_row_idx = 0
            best_score = -1
            best_headers: list[str] = []
            for i, row in enumerate(rows_to_scan):
                strs = [str(c).strip() for c in row if c is not None]
                # Header heuristic: count cells with 2-30 chars that don't look like full sentences
                header_like = sum(1 for s in strs if 2 <= len(s) <= 30 and len(s.split()) <= 4)
                if header_like > best_score:
                    best_score = header_like
                    best_row_idx = i + 1
                    best_headers = strs
            headers_per_sheet[sn] = best_headers
            likely_header_row_per_sheet[sn] = best_row_idx
        wb.close()
        return True, {
            "sheet_names": sheet_names,
            "sheet_info": sheet_info,
            "headers_per_sheet": headers_per_sheet,
            "likely_header_row_per_sheet": likely_header_row_per_sheet,
            "detected_format": detect_format(sheet_names),
        }
    except Exception as e:
        return False, {"error": f"{type(e).__name__}: {e}"[:300]}


def load_xls(path: Path) -> tuple[bool, dict[str, Any]]:
    """Try to load an old-format .xls via xlrd."""
    try:
        import xlrd  # type: ignore[import-untyped]

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            wb = xlrd.open_workbook(str(path))
        sheet_names = wb.sheet_names()
        sheet_info = {}
        headers_per_sheet = {}
        likely_header_row_per_sheet = {}
        for sn in sheet_names:
            ws = wb.sheet_by_name(sn)
            sheet_info[sn] = {"max_row": ws.nrows, "max_col": ws.ncols}
            best_score = -1
            best_idx = 0
            best_headers: list[str] = []
            for i in range(min(8, ws.nrows)):
                strs = [str(c).strip() for c in ws.row_values(i) if c not in ("", None)]
                header_like = sum(1 for s in strs if 2 <= len(s) <= 30 and len(s.split()) <= 4)
                if header_like > best_score:
                    best_score = header_like
                    best_idx = i + 1
                    best_headers = strs
            headers_per_sheet[sn] = best_headers
            likely_header_row_per_sheet[sn] = best_idx
        return True, {
            "sheet_names": sheet_names,
            "sheet_info": sheet_info,
            "headers_per_sheet": headers_per_sheet,
            "likely_header_row_per_sheet": likely_header_row_per_sheet,
            "detected_format": detect_format(sheet_names),
        }
    except Exception as e:
        return False, {"error": f"{type(e).__name__}: {e}"[:300]}


def load_pdf(path: Path) -> tuple[bool, dict[str, Any]]:
    """Try to extract text from a PDF. Flag image-only vs text-extractable."""
    try:
        import pdfplumber

        with pdfplumber.open(path) as pdf:
            n_pages = len(pdf.pages)
            total_text = ""
            n_with_text = 0
            tables_found = 0
            for page in pdf.pages:
                txt = page.extract_text() or ""
                if len(txt.strip()) > 20:
                    n_with_text += 1
                total_text += txt
                try:
                    page_tables = page.extract_tables() or []
                    tables_found += len(page_tables)
                except Exception:
                    pass
        text_density = len(total_text.strip()) / max(n_pages, 1)
        is_image_only = (n_with_text == 0) or (text_density < 50)
        return True, {
            "n_pages": n_pages,
            "n_pages_with_text": n_with_text,
            "text_chars": len(total_text),
            "text_density_per_page": text_density,
            "tables_extracted": tables_found,
            "is_image_only": is_image_only,
        }
    except Exception as e:
        return False, {"error": f"{type(e).__name__}: {e}"[:300]}


def classify_extension(path: Path) -> str:
    """Classify by extension, with macOS dupe-suffix normalization."""
    import re

    name = path.name.lower()
    # Strip macOS dupe suffix: ".xlsx(1)" → ".xlsx"
    name = re.sub(r"\.(xlsx|xls|pdf|docx)\(\d+\)$", lambda m: f".{m.group(1)}", name)
    ext = "." + name.rsplit(".", 1)[1] if "." in name else ""
    if ext == ".xlsx":
        return "xlsx"
    if ext == ".xls":
        return "xls"
    if ext == ".pdf":
        return "pdf"
    if ext == ".eml":
        return "eml"
    return "other"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("corpus_dir", help="Directory of cap-table files")
    parser.add_argument("-o", "--output", default=None, help="Write JSON report to file")
    parser.add_argument("--verbose", action="store_true", help="Print per-file progress")
    args = parser.parse_args()

    corpus = Path(args.corpus_dir)
    if not corpus.is_dir():
        print(f"ERROR: {corpus} is not a directory", file=sys.stderr)
        return 1

    files = sorted([f for f in corpus.iterdir() if f.is_file()])
    print(f"Scanning {len(files)} files in {corpus}", file=sys.stderr)

    results: list[dict[str, Any]] = []
    for f in files:
        ext_cls = classify_extension(f)
        ok = False
        info: dict[str, Any] = {}
        if ext_cls == "xlsx":
            ok, info = load_xlsx(f)
        elif ext_cls == "xls":
            ok, info = load_xls(f)
        elif ext_cls == "pdf":
            ok, info = load_pdf(f)
        else:
            info = {"skipped": f"unsupported extension {f.suffix}"}

        anon_name = f"file_{len(results):03d}"  # anonymize for output
        result = {
            "anon_name": anon_name,
            "extension_class": ext_cls,
            "file_size_bytes": f.stat().st_size,
            "loadable": ok,
            **info,
        }
        results.append(result)
        if args.verbose:
            status = "OK" if ok else "FAIL"
            print(f"  [{status}] {ext_cls:5s} {anon_name}: {f.name[:60]}", file=sys.stderr)

    # ------------------------------------------------------------------
    # Aggregate findings
    # ------------------------------------------------------------------
    by_ext: Counter[str] = Counter(r["extension_class"] for r in results)
    loadable_by_ext: Counter[str] = Counter(r["extension_class"] for r in results if r["loadable"])
    failed_by_ext: Counter[str] = Counter(r["extension_class"] for r in results if not r["loadable"])

    # Format-detection breakdown for xlsx/xls
    format_counts: Counter[str] = Counter()
    for r in results:
        if r["loadable"] and r["extension_class"] in {"xlsx", "xls"}:
            format_counts[r.get("detected_format", "unknown")] += 1

    # Sheet name popularity across the corpus (XLSX/XLS only).
    # Count DISTINCT FILES per name, then keep only names recurring in >= 3
    # files: company-specific names (Carta banner sheets, shareholder names
    # in misdetected header rows) don't recur across companies and would
    # leak real names into the report.
    sheet_name_counts: Counter[str] = Counter()
    column_header_counts: Counter[str] = Counter()
    for r in results:
        for sn in set(r.get("sheet_names", [])):
            sheet_name_counts[sn] += 1
        seen_headers: set[str] = set()
        for headers in r.get("headers_per_sheet", {}).values():
            for h in headers:
                if 2 <= len(h) <= 60:
                    seen_headers.add(h)
        for h in seen_headers:
            column_header_counts[h] += 1

    MIN_RECURRENCE = 3
    redacted_sheet_names = sum(1 for c in sheet_name_counts.values() if c < MIN_RECURRENCE)
    redacted_headers = sum(1 for c in column_header_counts.values() if c < MIN_RECURRENCE)
    sheet_name_counts = Counter({n: c for n, c in sheet_name_counts.items() if c >= MIN_RECURRENCE})
    column_header_counts = Counter({n: c for n, c in column_header_counts.items() if c >= MIN_RECURRENCE})

    # Reduce per-file inventories to counts — raw sheet/header names can
    # carry real company names and must not reach the report.
    for r in results:
        if "sheet_names" in r:
            r["n_sheets"] = len(r.pop("sheet_names"))
        if "headers_per_sheet" in r:
            r["n_header_columns_per_sheet"] = [len(v) for v in r.pop("headers_per_sheet").values()]
        if "sheet_info" in r:
            # dict keyed by raw sheet name → keep only the dimension values
            r["sheet_dimensions"] = list(r.pop("sheet_info").values())
        if "likely_header_row_per_sheet" in r:
            r["likely_header_rows"] = list(r.pop("likely_header_row_per_sheet").values())

    # PDF text-extractability
    pdf_results = [r for r in results if r["extension_class"] == "pdf"]
    pdf_loadable = sum(1 for r in pdf_results if r["loadable"])
    pdf_image_only = sum(1 for r in pdf_results if r["loadable"] and r.get("is_image_only"))
    pdf_with_tables = sum(1 for r in pdf_results if r["loadable"] and r.get("tables_extracted", 0) > 0)

    report: dict[str, Any] = {
        "corpus_dir": str(corpus),
        "total_files": len(files),
        "by_extension": dict(by_ext),
        "loadability": {
            "by_extension_ok": dict(loadable_by_ext),
            "by_extension_fail": dict(failed_by_ext),
            "overall_ok_pct": round(100 * sum(1 for r in results if r["loadable"]) / max(len(results), 1), 1),
        },
        "format_detection_xlsx_xls": dict(format_counts),
        "pdf_extractability": {
            "total_pdfs": len(pdf_results),
            "loadable": pdf_loadable,
            "image_only_or_low_text_density": pdf_image_only,
            "text_extractable": pdf_loadable - pdf_image_only,
            "with_extractable_tables": pdf_with_tables,
        },
        "top_30_sheet_names": sheet_name_counts.most_common(30),
        "top_50_column_headers": column_header_counts.most_common(50),
        "name_aggregation": {
            "min_recurrence_threshold": MIN_RECURRENCE,
            "sheet_names_redacted_below_threshold": redacted_sheet_names,
            "column_headers_redacted_below_threshold": redacted_headers,
        },
        "failures": [
            {"anon": r["anon_name"], "ext": r["extension_class"], "error": r.get("error", "")[:200]}
            for r in results
            if not r["loadable"]
        ],
        "per_file": results,
    }

    if args.output:
        out_path = os.path.abspath(args.output)
        with open(out_path, "w") as out_f:
            json.dump(report, out_f, indent=2, default=str)
        print(f"\nReport written to {out_path}", file=sys.stderr)

    # Human-readable summary to stderr
    print("\n" + "=" * 60, file=sys.stderr)
    print("CORPUS TEST SUMMARY", file=sys.stderr)
    print("=" * 60, file=sys.stderr)
    print(f"Total files: {len(files)}", file=sys.stderr)
    print(f"By extension: {dict(by_ext)}", file=sys.stderr)
    print(f"Loadable overall: {report['loadability']['overall_ok_pct']}%", file=sys.stderr)
    print(f"  XLSX OK: {loadable_by_ext.get('xlsx', 0)}/{by_ext.get('xlsx', 0)}", file=sys.stderr)
    print(f"  XLS  OK: {loadable_by_ext.get('xls', 0)}/{by_ext.get('xls', 0)}", file=sys.stderr)
    print(f"  PDF  OK: {loadable_by_ext.get('pdf', 0)}/{by_ext.get('pdf', 0)}", file=sys.stderr)
    print(f"Format detection (XLSX/XLS): {dict(format_counts)}", file=sys.stderr)
    print(
        f"PDFs: {pdf_loadable} loadable; "
        f"{pdf_image_only} image-only/low-text-density; "
        f"{pdf_with_tables} with extractable tables",
        file=sys.stderr,
    )
    print("\nTop 10 sheet names across corpus:", file=sys.stderr)
    for name, count in sheet_name_counts.most_common(10):
        print(f"  {count:3d}× {name}", file=sys.stderr)
    print("\nTop 20 column headers:", file=sys.stderr)
    for hdr, count in column_header_counts.most_common(20):
        print(f"  {count:3d}× {hdr}", file=sys.stderr)
    if failed_by_ext:
        print(f"\nFailures ({sum(failed_by_ext.values())} total):", file=sys.stderr)
        for r in results:
            if not r["loadable"]:
                print(f"  [{r['extension_class']}] {r['anon_name']}: {r.get('error', '')[:80]}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
