#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Privacy leak detector for commits / CI — without disclosing the names it guards.

Three layers, in order of value and precision:

  1. document  — a confidential-document file type (.xlsx/.pdf/.docx/…) tracked
                 anywhere outside a short, explicit allowlist of synthetic
                 fixtures. Catches real cap tables / term sheets dropped into the
                 repo. NAME-FREE — safe to run in CI.
  2. provenance — the "named-after-a-real-thing" anti-pattern in text:
                 "the Acmecorp P-1 failure", "the R-5 shape", round/case IDs.
                 NAME-FREE — safe to run in CI. (Conservative; bypass a false
                 positive with `git commit --no-verify`.)
  3. name      — an exact real company name from a LOCAL denylist file that is
                 never committed (lives in the already-git-ignored docs/internal/).
                 The detector logic ships in the repo; the names do NOT. CI has no
                 list, so layer 3 simply no-ops there.

Usage:
  privacy_guard.py --staged              # scan git-staged files (pre-commit hook)
  privacy_guard.py --tree                # scan all tracked files (CI; layers 1+2)
  privacy_guard.py FILE [FILE ...]       # scan specific files
  privacy_guard.py --staged --names-file docs/internal/privacy-denylist.txt
  privacy_guard.py --tree --no-names     # force-skip layer 3

Exit 0 = clean, 1 = findings (printed to stderr), 2 = usage error.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass

# Confidential document file types. .csv is intentionally excluded (commonly
# legitimate structured test data); add it here if that changes.
DOC_EXTS = {".xlsx", ".xls", ".pdf", ".docx", ".doc", ".pptx", ".ppt", ".numbers", ".key"}

# The ONLY document-type files allowed in the tracked tree — all synthetic
# fixtures. A new doc file must be added here deliberately (that is the point:
# it forces a conscious "is this synthetic?" decision at review time).
ALLOWLISTED_DOCS = frozenset(
    {
        "cowork-tests/fixtures/carta-folder/synthetic_carta.xlsx",
        "cowork-tests/fixtures/freeform_lane3.xlsx",
        "cowork-tests/fixtures/safe_cap_plus_discount.pdf",
        "cowork-tests/fixtures/sample_model.xlsx",
        "cowork-tests/fixtures/synthetic_carta.xlsx",
        "cowork-tests/fixtures/term_sheet_blank_exclusivity.pdf",
        "founder-skills/tests/fixtures/cap-table-corpus/synthetic_carta.xlsx",
        "founder-skills/tests/fixtures/sample_model.xlsx",
        # Landing-page capture fixtures. Fictional Acmecorp; generated by
        # tools/landing-capture/fixtures/build_xlsx.py, never hand-edited.
        "tools/landing-capture/fixtures/acmecorp-cap-table.xlsx",
        "tools/landing-capture/fixtures/acmecorp-model.xlsx",
    }
)

DEFAULT_NAMES_FILE = "docs/internal/privacy-denylist.txt"

# Layer-2 pattern (name-free, HIGH PRECISION — it gates commits, so generic
# English must not trip it). It catches the observed "named-after-an-unknown-
# company" leak shape: "the <ProperNoun> [P-1] failure/shape/…". The token after
# "the" must be a Capitalized proper noun (mid-sentence) — so "the same shape",
# "the bug shape", "the exact shape" do NOT match. A common false-friend
# (capitalized library/tool name) is bypassable with `git commit --no-verify`.
# Known real names are caught precisely by layer 3, so this is defense-in-depth
# for names not yet on the local list. Version/round-ID policing is deliberately
# out of scope here (a privacy guard, not a provenance linter).
_PROV_NOUN = r"(?:failure|shape|bug|incident|saga|episode|fiasco|debacle|case|deal)"
PROVENANCE_PATTERNS = [
    # The full antipattern triple is REQUIRED: <ProperNoun> + <round/case-ID> +
    # <failure-word>, e.g. "the Acmecorp P-1 failure". Requiring the ID is what
    # keeps "the Carta shape" / "the JSON shape" (proper noun, no ID) from
    # tripping it. Known names are caught precisely by layer 3 regardless.
    re.compile(rf"\bthe\s+[A-Z][A-Za-z]{{2,}}(?:[/-][A-Za-z]+)?\s+[PR]-\d{{1,3}}\s+{_PROV_NOUN}\b"),
]

# Files whose own job is to describe these patterns — exempt from layer 2 so the
# guard and its tests don't flag themselves.
_SELF_EXEMPT = {"scripts/privacy_guard.py", "scripts/test_privacy_guard.py"}

_TEXT_SKIP_EXTS = DOC_EXTS | {".png", ".jpg", ".jpeg", ".gif", ".woff", ".woff2", ".ttf", ".otf", ".ico", ".zip", ".gz"}


@dataclass
class Finding:
    path: str
    layer: str  # "document" | "provenance" | "name"
    detail: str


def load_names(path: str) -> list[str]:
    """Load the local denylist (one name per line, # comments, blanks ignored).
    Missing file → empty list (so CI, which has no list, simply skips layer 3)."""
    if not os.path.isfile(path):
        return []
    names: list[str] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if s and not s.startswith("#"):
                names.append(s)
    return names


def _ext(path: str) -> str:
    return os.path.splitext(path)[1].lower()


def find_document_violations(paths: list[str]) -> list[Finding]:
    out = []
    for p in paths:
        if _ext(p) in DOC_EXTS and p not in ALLOWLISTED_DOCS:
            out.append(Finding(p, "document", f"confidential document type not in allowlist ({_ext(p)})"))
    return out


def find_provenance(path: str, text: str) -> list[Finding]:
    if path in _SELF_EXEMPT:
        return []
    out = []
    for pat in PROVENANCE_PATTERNS:
        m = pat.search(text)
        if m:
            out.append(Finding(path, "provenance", f"provenance/named-after tag: {m.group(0)!r}"))
            break
    return out


def find_names(path: str, text: str, names: list[str]) -> list[Finding]:
    if path in _SELF_EXEMPT or not names:
        return []
    low = text.lower()
    for name in names:
        # whole-word, case-insensitive
        if re.search(rf"(?<![\w]){re.escape(name.lower())}(?![\w])", low):
            out_detail = "matches a locally-denylisted real name"
            return [Finding(path, "name", out_detail)]
    return []


def scan_text_and_paths(paths: list[str], contents: dict[str, str], names: list[str]) -> list[Finding]:
    """Pure core: classify a set of paths + their text contents. `contents` maps
    path→text for text files (binary/doc files omitted)."""
    findings: list[Finding] = []
    findings.extend(find_document_violations(paths))
    for p in paths:
        # Layer 3 on the PATH too: a denylisted name in a file/dir name (a fixture
        # named after the real company) must be caught even with no matching text.
        # Normalize separators to spaces so path tokens are whole-word-bounded.
        path_tokens = re.sub(r"[/_.\-]+", " ", p)
        findings.extend(find_names(p, path_tokens, names))
        text = contents.get(p)
        if text is None:
            continue
        findings.extend(find_provenance(p, text))
        findings.extend(find_names(p, text, names))
    return findings


def _read_text(path: str) -> str | None:
    if _ext(path) in _TEXT_SKIP_EXTS:
        return None
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except (OSError, UnicodeDecodeError):
        return None


def _git_files(staged: bool) -> list[str]:
    cmd = ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"] if staged else ["git", "ls-files"]
    out = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
    return [line for line in out.splitlines() if line]


def scan(paths: list[str], names: list[str]) -> list[Finding]:
    contents = {p: t for p in paths if (t := _read_text(p)) is not None}
    return scan_text_and_paths(paths, contents, names)


def _main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Privacy leak detector (pre-commit / CI).")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--staged", action="store_true", help="scan git-staged files")
    g.add_argument("--tree", action="store_true", help="scan all tracked files")
    ap.add_argument("files", nargs="*", help="explicit files to scan")
    ap.add_argument("--names-file", default=DEFAULT_NAMES_FILE, help="local denylist path")
    ap.add_argument("--no-names", action="store_true", help="skip layer 3 (name list)")
    args = ap.parse_args(argv)

    if args.staged or args.tree:
        paths = _git_files(staged=args.staged)
    elif args.files:
        paths = args.files
    else:
        ap.error("provide --staged, --tree, or explicit files")
        return 2

    names = [] if args.no_names else load_names(args.names_file)
    findings = scan(paths, names)

    if findings:
        print("✗ privacy-guard: potential leak(s) detected:\n", file=sys.stderr)
        for f in findings:
            print(f"  [{f.layer:<10}] {f.path}\n               {f.detail}", file=sys.stderr)
        print(
            "\nFix the file, or — if this is a confirmed false positive — bypass with `git commit --no-verify`.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(_main())
